-- MySQL Script generated by MySQL Workbench
-- Tue Feb 16 11:27:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_pizzaria_legal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_pizzaria_legal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_pizzaria_legal` DEFAULT CHARACTER SET utf8 ;
USE `db_pizzaria_legal` ;

-- -----------------------------------------------------
-- Table `db_pizzaria_legal`.`tb_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzaria_legal`.`tb_categorias` (
  `idtb_categorias` INT NOT NULL AUTO_INCREMENT,
  `Salgadas` VARCHAR(45) NOT NULL,
  `Doces` VARCHAR(45) NOT NULL,
  `Mista` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtb_categorias`),
  UNIQUE INDEX `idtb_categorias_UNIQUE` (`idtb_categorias` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pizzaria_legal`.`tb_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzaria_legal`.`tb_pizza` (
  `idtb_pizza` INT NOT NULL AUTO_INCREMENT,
  `nome_pizza` VARCHAR(45) NOT NULL,
  `tamanho_pizza` VARCHAR(45) NOT NULL,
  `valor_pizza` VARCHAR(45) NOT NULL,
  `combo_pizza` VARCHAR(45) NOT NULL,
  `pizza_festa` VARCHAR(45) NOT NULL,
  `tb_categorias_idtb_categorias` INT NOT NULL,
  PRIMARY KEY (`idtb_pizza`, `tb_categorias_idtb_categorias`),
  UNIQUE INDEX `idtb_pizza_UNIQUE` (`idtb_pizza` ASC) VISIBLE,
  INDEX `fk_tb_pizza_tb_categorias_idx` (`tb_categorias_idtb_categorias` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pizza_tb_categorias`
    FOREIGN KEY (`tb_categorias_idtb_categorias`)
    REFERENCES `db_pizzaria_legal`.`tb_categorias` (`idtb_categorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
